---
version: '3'
services:

  elasticsearch:
    build: elasticsearch/
    volumes:
     - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports: ['127.0.0.1:9200:9200']
    networks: ['stack']

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports: ['127.0.0.1:5601:5601']
    networks: ['stack']
    depends_on: ['elasticsearch']

  logstash:
    build: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports: 
      - '127.0.0.1:5000:5000'
      - '127.0.0.1:5001:5001'
      - '127.0.0.1:5002:5002/udp'
    networks: ['stack']
    depends_on: ['elasticsearch']

networks: {stack: {}}
