version: '3'
services:

  elasticsearch:
    build: elasticsearch/
    volumes:
     - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports: ['0.0.0.0:9200:9200']
    networks: ['stack']

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports: ['0.0.0.0:5601:5601']
    networks: ['stack']
    depends_on: ['elasticsearch']

  logstash:
    build: logstash/
    volumes:
      - ./logstash/config/:/usr/share/logstash/config/
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
    ports:
      - '0.0.0.0:5000:5000'
      - '0.0.0.0:5001:5001'
      - '0.0.0.0:5002:5002/udp'
    networks: ['stack']
    depends_on: ['elasticsearch']

networks: {stack: {}}
