---
version: '3'
services:

  elasticsearch:
    build: elasticsearch/
    volumes:
     - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}']
    ports: ['127.0.0.1:9200:9200']
    networks: ['stack']

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    environment: ['ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}']
    ports: ['127.0.0.1:5601:5601']
    networks: ['stack']
    depends_on: ['elasticsearch']

  logstash:
    build: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - 'xpack.monitoring.elasticsearch.password=${ELASTIC_PASSWORD}'
    ports: 
      - '127.0.0.1:5000:5000'
      - '127.0.0.1:5001:5001'
      - '127.0.0.1:5002:5002/udp'
    
    # Provide a simple pipeline configuration for Logstash with a bind-mounted file.
    networks: ['stack']
    depends_on: ['elasticsearch']

networks: {stack: {}}
