# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/logstash/logstash:6.1.1

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json

#RUN logstash-plugin install logstash-codec-netflow
#RUN logstash-plugin install logstash-filter-translate
#RUN logstash-plugin install logstash-filter-cidr
#RUN logstash-plugin install logstash-filter-geoip
